# server:
#   port: 8080

server:
  # Key-Value形式
  # server: {port: 8080}
  port: 8080
  address: 127.0.0.1

  # 数组形式
  # openports: [8081, 8082]
  openPorts:
    - 8081
    - 8082
  serverName: 'Production' # 单引号忽略转义字符
  # serverName: "Test-Stage" 双引号识别转义字符

  # 复杂形式
  dockerConfigs:
    -
      name: ${server.serverName}-docker1
      ipAddress: 192.168.31.101
    -
      name: ${server.serverName}-docker2
      ipAddress: 192.168.31.102