server:
  # Key-Value形式
  # server: {port: 8080}
  port: 12321
  address:
    - 127.0.0.1
    - localhost

  # 数组形式
  # open-ports: [8081, 8082]
  open-ports:
    - 8081
    - 8082
  serverName: 'Local' # 单引号忽略转义字符
  # serverName: "Test-Stage: \nLocal" # 双引号识别转义字符

  # 复杂形式
  dockerConfigs:
    - name: ${server.serverName}-docker1
      ip-address: 192.168.31.101
    - name: ${server.serverName}-docker2
      ip-address: 192.168.31.102
    - {name: docker3, ipAddress: 192.168.31.103}
#   此处也可以配置为这种one-line形式，但是在实际测试中发现$符号无法被识别，报错
#   - {name: ${server.serverName}-docker3, ipAddress: 192.168.31.103}