server:
  port: 12323
  address:
    - 192.168.31.150
    - localhost
  open-ports:
    - 8084
    - 8085
  serverName: "Production"
  dockerConfigs:
    - name: ${server.serverName}-docker1
      ip-address: 192.168.31.101
    - name: ${server.serverName}-docker2
      ip-address: 192.168.31.102
    - { name: docker3, ipAddress: 192.168.31.103 }
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        exclude:
info:
  name: ${server.serverName} Server
  address: ${server.address[0]}